function Question(r)
{
  this.text=table.getString(r,0);
  this.money=parseInt(table.getString(r,1));
  if(this.money==999)
    this.money=ceil(random(20)-10);
  this.people=parseInt(table.getString(r,2));
  if(this.people==999)
    this.people=ceil(random(20)-10);
  this.clergy=parseInt(table.getString(r,3));
  if(this.clergy==999)
    this.clergy=ceil(random(20)-10);
  this.army=parseInt(table.getString(r,4));
  if(this.army==999)
    this.army=ceil(random(20)-10);
  this.yes=function(verdad)
  {
    if(verdad==true)
    { 
      if(player.money+this.money>ceiling)
        player.money=ceiling;
      else
        player.money+=this.money;
      if(player.people+this.people>ceiling)
        player.people=ceiling;
      else
        player.people+=this.people;
      if(player.clergy+this.clergy>ceiling)
        player.clergy=ceiling;
      else
        player.clergy+=this.clergy;
      if(player.army+this.army>ceiling)
        player.army=ceiling;
      else
        player.army+=this.army;
    }
    else
    {
      if(player.money-this.money>ceiling)
        player.money=ceiling;
      else
        player.money-=this.money;
      if(player.people-this.people>ceiling)
        player.people=ceiling;
      else
        player.people-=this.people;
      if(player.clergy-this.clergy>ceiling)
        player.clergy=ceiling;
      else
        player.clergy-=this.clergy;
      if(player.army-this.army>ceiling)
        player.army=ceiling;
      else
        player.army-=this.army;
    }
  }
}